apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: Client Tax Reporting - IT
    openshift.io/requester: developer
    openshift.io/sa.scc.mcs: s0:c15,c5
    openshift.io/sa.scc.supplemental-groups: 1000220000/10000
    openshift.io/sa.scc.uid-range: 1000220000/10000
  creationTimestamp: null
  name: ctr-it
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
