apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: High Sensitivity
    openshift.io/display-name: Client Tax Reporting - PROD
    openshift.io/sa.scc.mcs: s1:c11,6
  creationTimestamp: null
  name: ctr-prod
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
