apiVersion: v1
kind: Template
metadata:
  name: rabbitmq
labels:
  template: rabbitmq
  app: rabbitmq
metadata:
  annotations:
    description: Creates RabbitMQ instance for messaging
    iconClass: icon-rabbitmq
    tags: rabbitmq
  name: rabbitmq
message: RabbitMQ instances for DEV and IT
parameters:
- description: Password for the RabbitMQ admin user.
  displayName: RabbitMQ Admin Password
  value: password
  name: RABBITMQ_ADMIN_PASSWORD
  required: true
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
    labels:
      app: rabbitmq
  spec:
    ports:
    - name: client
      nodePort: 0
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management-console
      nodePort: 0
      port: 15672
      protocol: TCP
      targetPort: 15672
    selector:
      name: rabbitmq
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: rabbitmq
    labels:
      app: rabbitmq
  spec:
    port:
      targetPort: management-console
    to:
      kind: Service
      name: rabbitmq
      port: 15672
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rabbitmq
    labels:
      app: rabbitmq
  spec:
    replicas: 1
    selector:
      name: rabbitmq
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: rabbitmq
      spec:
        containers:
        - capabilities: {}
          env:
          - name: RABBITMQ_PASS
            value: ${RABBITMQ_ADMIN_PASSWORD}
          image: 'rabbitmq:3.6.11-management-alpine'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 15672
            initialDelaySeconds: 120
            timeoutSeconds: 3
          name: rabbitmq
          readinessProbe:
            httpGet:
              path: /
              port: 15672
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
