apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for application pipeline service accounts, all it can do is
      add an image to the imagestream, that is it
  creationTimestamp: null
  name: application-pipeline
rules:
- apiGroups:
  - image.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - imagestreams/layers
  verbs:
  - get
  - update
- apiGroups:
  - image.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - imagestreams
  verbs:
  - get
  - create