apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ocr
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfs-data/pv-ocr
    server: 10.99.47.221
  persistentVolumeReclaimPolicy: Recycle