apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv12
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfs-data/pv12
    server: 10.99.47.221
  persistentVolumeReclaimPolicy: Recycle