apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv08
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/nfs-data/pv08
    server: 10.99.47.221
  persistentVolumeReclaimPolicy: Recycle